# Generated by Django 5.0.14 on 2025-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[("react", "React Page"), ("markdown", "Markdown")],
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="For React: paste your React component code. For Markdown: paste markdown content."
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive content won't show on dashboard",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Content",
                "ordering": ["order", "title"],
            },
        ),
    ]
