# Generated by Django 5.0.14 on 2025-10-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Link to car listing", max_length=500),
                ),
                ("year", models.IntegerField(help_text="Year of manufacture")),
                ("mileage", models.IntegerField(help_text="Current mileage")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Asking price", max_digits=10
                    ),
                ),
                (
                    "dealer",
                    models.CharField(help_text="Dealer or seller name", max_length=200),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Cars",
                "ordering": ["-created_at"],
            },
        ),
    ]
