# Generated by Django 5.0.14 on 2025-10-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="comparison_notes",
            field=models.TextField(
                blank=True,
                help_text="Auto-generated comparison notes (pros/cons based on criteria)",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="ground_clearance",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Ground clearance in inches (e.g., 8.7)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="make",
            field=models.CharField(
                default="",
                help_text="Manufacturer (e.g., Subaru, Honda)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(
                default="",
                help_text="Model name (e.g., Forester, Outback)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="mpg_city",
            field=models.IntegerField(blank=True, help_text="City MPG", null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="mpg_highway",
            field=models.IntegerField(blank=True, help_text="Highway MPG", null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="recommendation",
            field=models.CharField(
                choices=[
                    ("excellent", "🏆 Excellent - Highly Recommended"),
                    ("good", "✅ Good - Recommended"),
                    ("acceptable", "⚠️ Acceptable - OK with Conditions"),
                    ("avoid", "❌ Avoid - Not Recommended"),
                ],
                default="acceptable",
                help_text="Overall recommendation based on cold-climate criteria",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="reliability_rating",
            field=models.IntegerField(
                default=5,
                help_text="Reliability rating (1-10): Check year-specific issues",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="trim",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trim level (e.g., 2.5i Premium)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="winter_rating",
            field=models.IntegerField(
                default=5,
                help_text="Winter/snow performance (1-10): Subarus=10, AWD SUVs=7-8, FWD=3-5",
            ),
        ),
    ]
