# Generated by Django 5.0.14 on 2025-10-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_car_comparison_notes_car_ground_clearance_car_make_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="stock",
            field=models.CharField(
                blank=True, default="", help_text="Dealer stock number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="vin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vehicle Identification Number",
                max_length=17,
            ),
        ),
    ]
