# Generated by Django 5.0.14 on 2025-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_car_stock_car_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="combined_mpg",
            field=models.IntegerField(
                blank=True,
                help_text="Combined MPG (auto-calculated or manual override)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="maintenance_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated annual maintenance cost (e.g., 800.00)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
